[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = []

[phases.build]
cmds = [
  'npm install -g pnpm@11.1.1',
  'pnpm install --frozen-lockfile',
  'pnpm --filter api build'
]

[start]
cmd = 'node apps/api/dist/index.js'
